# Generated by Django 2.1.4 on 2019-02-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='dialog',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialog_messages', to='user_messages.Dialogs', verbose_name='Диалог'),
        ),
    ]
