# Generated by Django 2.1.4 on 2019-02-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20190118_1507'),
        ('classified', '0007_auto_20190118_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название магазина')),
                ('our_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон магазина')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(max_length=240, verbose_name='SEO описание')),
                ('blog_active', models.BooleanField(default=False, verbose_name='Актировать блог')),
                ('pages_menu', models.ManyToManyField(to='category.Category', verbose_name='Страницы в меню')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
