# Generated by Django 2.1.4 on 2019-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0008_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='pages_menu',
            field=models.ManyToManyField(to='pages.Pages', verbose_name='Страницы в меню'),
        ),
    ]
